# Проект Исследование надежности заемщиков №2

Во второй части проекта вы выполните шаги 3 и 4. Их вручную проверит ревьюер.
Чтобы вам не пришлось писать код заново для шагов 1 и 2, мы добавили авторские решения в ячейки с кодом.

## Откройте таблицу и изучите общую информацию о данных

**Задание 1. Импортируйте библиотеку pandas. Считайте данные из csv-файла в датафрейм и сохраните в переменную `data`. Путь к файлу:**

`/datasets/data.csv`

In [1]:
import pandas as pd

In [2]:
try:
    data = pd.read_csv('/datasets/data.csv')
except:
    data = pd.read_csv('https://code.s3.yandex.net/datasets/data.csv')

**Задание 2. Выведите первые 20 строчек датафрейма `data` на экран.**

In [3]:
data.head(20)

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
0,1,-8437.673028,42,высшее,0,женат / замужем,0,F,сотрудник,0,253875.639453,покупка жилья
1,1,-4024.803754,36,среднее,1,женат / замужем,0,F,сотрудник,0,112080.014102,приобретение автомобиля
2,0,-5623.422610,33,Среднее,1,женат / замужем,0,M,сотрудник,0,145885.952297,покупка жилья
3,3,-4124.747207,32,среднее,1,женат / замужем,0,M,сотрудник,0,267628.550329,дополнительное образование
4,0,340266.072047,53,среднее,1,гражданский брак,1,F,пенсионер,0,158616.077870,сыграть свадьбу
5,0,-926.185831,27,высшее,0,гражданский брак,1,M,компаньон,0,255763.565419,покупка жилья
6,0,-2879.202052,43,высшее,0,женат / замужем,0,F,компаньон,0,240525.971920,операции с жильем
7,0,-152.779569,50,СРЕДНЕЕ,1,женат / замужем,0,M,сотрудник,0,135823.934197,образование
8,2,-6929.865299,35,ВЫСШЕЕ,0,гражданский брак,1,F,сотрудник,0,95856.832424,на проведение свадьбы
9,0,-2188.756445,41,среднее,1,женат / замужем,0,M,сотрудник,0,144425.938277,покупка жилья для семьи
10,2,-4171.483647,36,высшее,0,женат / замужем,0,M,компаньон,0,113943.491460,покупка недвижимости
11,0,-792.701887,40,среднее,1,женат / замужем,0,F,сотрудник,0,77069.234271,покупка коммерческой недвижимости
12,0,NaN,65,среднее,1,гражданский брак,1,M,пенсионер,0,NaN,сыграть свадьбу
13,0,-1846.641941,54,неоконченное высшее,2,женат / замужем,0,F,сотрудник,0,130458.228857,приобретение автомобиля
14,0,-1844.956182,56,высшее,0,гражданский брак,1,F,компаньон,1,165127.911772,покупка жилой недвижимости
15,1,-972.364419,26,среднее,1,женат / замужем,0,F,сотрудник,0,116820.904450,строительство собственной недвижимости
16,0,-1719.934226,35,среднее,1,женат / замужем,0,F,сотрудник,0,289202.704229,недвижимость
17,0,-2369.999720,33,высшее,0,гражданский брак,1,M,сотрудник,0,90410.586745,строительство недвижимости
18,0,400281.136913,53,среднее,1,вдовец / вдова,2,F,пенсионер,0,56823.777243,на покупку подержанного автомобиля
19,0,-10038.818549,48,СРЕДНЕЕ,1,в разводе,3,F,сотрудник,0,242831.107982,на покупку своего автомобиля

**Задание 3. Выведите основную информацию о датафрейме с помощью метода `info()`.**

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   children          21525 non-null  int64
 1   days_employed     19351 non-null  float64
 2   dob_years         21525 non-null  int64
 3   education         21525 non-null  object
 4   education_id      21525 non-null  int64
 5   family_status     21525 non-null  object
 6   family_status_id  21525 non-null  int64
 7   gender            21525 non-null  object
 8   income_type       21525 non-null  object
 9   debt              21525 non-null  int64
 10  total_income      19351 non-null  float64
 11  purpose           21525 non-null  object
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB

## Предобработка данных

### Удаление пропусков

**Задание 4. Выведите количество пропущенных значений для каждого столбца. Используйте комбинацию двух методов.**

In [5]:
data.isna().sum()

children               0
days_employed       2174
dob_years              0
education              0
education_id           0
family_status          0
family_status_id       0
gender                 0
income_type            0
debt                   0
total_income        2174
purpose                0
dtype: int64

**Задание 5. В двух столбцах есть пропущенные значения. Один из них — `days_employed`. Пропуски в этом столбце вы обработаете на следующем этапе. Другой столбец с пропущенными значениями — `total_income` — хранит данные о доходах. На сумму дохода сильнее всего влияет тип занятости, поэтому заполнить пропуски в этом столбце нужно медианным значением по каждому типу из столбца `income_type`. Например, у человека с типом занятости `сотрудник` пропуск в столбце `total_income` должен быть заполнен медианным доходом среди всех записей с тем же типом.**

In [6]:
for t in data['income_type'].unique():
    data.loc[(data['income_type'] == t) & (data['total_income'].isna()), 'total_income'] = \
    data.loc[(data['income_type'] == t), 'total_income'].median()

### Обработка аномальных значений

**Задание 6. В данных могут встречаться артефакты (аномалии) — значения, которые не отражают действительность и появились по какой-то ошибке. таким артефактом будет отрицательное количество дней трудового стажа в столбце `days_employed`. Для реальных данных это нормально. Обработайте значения в этом столбце: замените все отрицательные значения положительными с помощью метода `abs()`.**

In [7]:
data['days_employed'] = data['days_employed'].abs()

**Задание 7. Для каждого типа занятости выведите медианное значение трудового стажа `days_employed` в днях.**

In [8]:
data.groupby('income_type')['days_employed'].agg('median')

income_type
безработный        366413.652744
в декрете            3296.759962
госслужащий          2689.368353
компаньон            1547.382223
пенсионер          365213.306266
предприниматель       520.848083
сотрудник            1574.202821
студент               578.751554
Name: days_employed, dtype: float64

У двух типов (безработные и пенсионеры) получатся аномально большие значения. Исправить такие значения сложно, поэтому оставьте их как есть. Тем более этот столбец не понадобится вам для исследования.

**Задание 8. Выведите перечень уникальных значений столбца `children`.**

In [9]:
data['children'].unique()

array([ 1,  0,  3,  2, -1,  4, 20,  5], dtype=int64)

**Задание 9. В столбце `children` есть два аномальных значения. Удалите строки, в которых встречаются такие аномальные значения из датафрейма `data`.**

In [10]:
data = data[(data['children'] != -1) & (data['children'] != 20)]

**Задание 10. Ещё раз выведите перечень уникальных значений столбца `children`, чтобы убедиться, что артефакты удалены.**

In [11]:
data['children'].unique()

array([1, 0, 3, 2, 4, 5], dtype=int64)

### Удаление пропусков (продолжение)

**Задание 11. Заполните пропуски в столбце `days_employed` медианными значениями по каждого типа занятости `income_type`.**

In [12]:
for t in data['income_type'].unique():
    data.loc[(data['income_type'] == t) & (data['days_employed'].isna()), 'days_employed'] = \
    data.loc[(data['income_type'] == t), 'days_employed'].median()

**Задание 12. Убедитесь, что все пропуски заполнены. Проверьте себя и ещё раз выведите количество пропущенных значений для каждого столбца с помощью двух методов.**

In [13]:
data.isna().sum()

children            0
days_employed       0
dob_years           0
education           0
education_id        0
family_status       0
family_status_id    0
gender              0
income_type         0
debt                0
total_income        0
purpose             0
dtype: int64

### Изменение типов данных

**Задание 13. Замените вещественный тип данных в столбце `total_income` на целочисленный с помощью метода `astype()`.**

In [14]:
data['total_income'] = data['total_income'].astype(int)

### Обработка дубликатов

**Задание 14. Обработайте неявные дубликаты в столбце `education`. В этом столбце есть одни и те же значения, но записанные по-разному: с использованием заглавных и строчных букв. Приведите их к нижнему регистру. Проверьте остальные столбцы.**

In [15]:
data['education'] = data['education'].str.lower()

**Задание 15. Выведите на экран количество строк-дубликатов в данных. Если такие строки присутствуют, удалите их.**

In [16]:
data.duplicated().sum()

71

In [17]:
data = data.drop_duplicates()

### Категоризация данных

**Задание 16. На основании диапазонов, указанных ниже, создайте в датафрейме `data` столбец `total_income_category` с категориями:**

- 0–30000 — `'E'`;
- 30001–50000 — `'D'`;
- 50001–200000 — `'C'`;
- 200001–1000000 — `'B'`;
- 1000001 и выше — `'A'`.


**Например, кредитополучателю с доходом 25000 нужно назначить категорию `'E'`, а клиенту, получающему 235000, — `'B'`. Используйте собственную функцию с именем `categorize_income()` и метод `apply()`.**

In [18]:
def categorize_income(income):
    try:
        if 0 <= income <= 30000:
            return 'E'
        elif 30001 <= income <= 50000:
            return 'D'
        elif 50001 <= income <= 200000:
            return 'C'
        elif 200001 <= income <= 1000000:
            return 'B'
        elif income >= 1000001:
            return 'A'
    except:
        pass

In [19]:
data['total_income_category'] = data['total_income'].apply(categorize_income)

**Задание 17. Выведите на экран перечень уникальных целей взятия кредита из столбца `purpose`.**

In [20]:
data['purpose'].unique()

array(['покупка жилья', 'приобретение автомобиля',
       'дополнительное образование', 'сыграть свадьбу',
       'операции с жильем', 'образование', 'на проведение свадьбы',
       'покупка жилья для семьи', 'покупка недвижимости',
       'покупка коммерческой недвижимости', 'покупка жилой недвижимости',
       'строительство собственной недвижимости', 'недвижимость',
       'строительство недвижимости', 'на покупку подержанного автомобиля',
       'на покупку своего автомобиля',
       'операции с коммерческой недвижимостью',
       'строительство жилой недвижимости', 'жилье',
       'операции со своей недвижимостью', 'автомобили',
       'заняться образованием', 'сделка с подержанным автомобилем',
       'получение образования', 'автомобиль', 'свадьба',
       'получение дополнительного образования', 'покупка своего жилья',
       'операции с недвижимостью', 'получение высшего образования',
       'свой автомобиль', 'сделка с автомобилем',
       'профильное образование', 'высшее образование',
       'покупка жилья для сдачи', 'на покупку автомобиля', 'ремонт жилью',
       'заняться высшим образованием'], dtype=object)

**Задание 18. Создайте функцию, которая на основании данных из столбца `purpose` сформирует новый столбец `purpose_category`, в который войдут следующие категории:**

- `'операции с автомобилем'`,
- `'операции с недвижимостью'`,
- `'проведение свадьбы'`,
- `'получение образования'`.

**Например, если в столбце `purpose` находится подстрока `'на покупку автомобиля'`, то в столбце `purpose_category` должна появиться строка `'операции с автомобилем'`.**

**Используйте собственную функцию с именем `categorize_purpose()` и метод `apply()`. Изучите данные в столбце `purpose` и определите, какие подстроки помогут вам правильно определить категорию.**

In [21]:
def categorize_purpose(row):
    try:
        if 'автом' in row:
            return 'операции с автомобилем'
        elif 'жил' in row or 'недвиж' in row:
            return 'операции с недвижимостью'
        elif 'свад' in row:
            return 'проведение свадьбы'
        elif 'образов' in row:
            return 'получение образования'
    except:
        return 'нет категории'

In [22]:
data['purpose_category'] = data['purpose'].apply(categorize_purpose)

## Шаг 3. Исследуйте данные и ответьте на вопросы

### Есть ли зависимость между количеством детей и возвратом кредита в срок?

In [23]:
target = data.pivot_table(index = [ 'children'], values = 'debt', aggfunc = {'count','sum'})
target = target.rename(columns={'count':'total','sum':'target'})
target['share'] = round(target['target']/target['total'], 3)
target = target.sort_values(by='share')
display(target)

          total  target  share
children
5             9       0  0.000
0         14091    1063  0.075
3           330      27  0.082
1          4808     444  0.092
2          2052     194  0.095
4            41       4  0.098

Сделав сводную таблицу и проанализировав пропорцию возврата кредита в срок в зависимости от количества детей, можно сделать следующие выводы:

- Количество детей влияет на возврат кредита в срок. Люди без детей имеют наименьший процент задолженностей (7.5%), а с увеличением детей процент задолженностей постепенно растёт.

1. Самый высокий процент задолженностей наблюдается у клиентов с 4 детьми (9.8%).
2. Самый низкий процент задолженностей (7.5%) у клиентов без детей.
3. Клиенты без детей либо с 1-2 детьми имеют промежуточные значения процента задолженностей (7.5%, 9.2% и 9.5% соответственно). Можно сказать, что клиенты без детей имеют немного более низкую долю задолженности по сравнению с клиентами с одним или двумя детьми. Однако разница не является значительной и требует более детального анализа и изучения других факторов, таких как уровень дохода, тип занятости и т.д., для более точной оценки влияния наличия детей на вероятность задолженности по кредиту.

Таким образом, можно сделать вывод, что наличие детей влияет на финансовую стабильность и способность возвратить кредит в срок. Чем больше детей у заемщика, тем выше вероятность задолженности по кредиту.

### Есть ли зависимость между семейным положением и возвратом кредита в срок?

In [24]:
target = data.pivot_table(index = [ 'family_status'], values = 'debt', aggfunc = {'count','sum'})
target = target.rename(columns={'count':'total','sum':'target'})
target['share'] = round(target['target']/target['total'], 3)
target = target.sort_values(by='share', ascending=True)
display(target)

                       total  target  share
family_status
вдовец / вдова           951      63  0.066
в разводе               1189      84  0.071
женат / замужем        12261     927  0.076
гражданский брак        4134     385  0.093
Не женат / не замужем   2796     273  0.098

Группа людей, состоящих в браке, имеет наименьший процент просрочек по задолженностям. В то же время, люди, которые никогда не вступали в брак или находятся в гражданском браке, имеют максимальную задолженность.

Эти результаты могут быть объяснены несколькими факторами. Вступление в брак обычно сопровождается большей финансовой стабильностью, так как супруги могут объединить свои ресурсы и распределить ответственность за финансовые обязательства. Более тесные семейные связи и поддержка также могут способствовать более дисциплинированному подходу к управлению финансами.

С другой стороны, люди, которые никогда не вступали в брак или находятся в гражданском браке, могут испытывать больше финансовых трудностей. Они не имеют преимуществ совместного управления финансами или поддержки партнера, что может привести к более высокому уровню задолженности.
    
В целом, эти результаты указывают на то, что брак может играть положительную роль в финансовой стабильности и управлении долгами. Однако, следует отметить, что каждая ситуация индивидуальна, и наличие или отсутствие брака не является единственным определяющим фактором финансового положения человека.

### Есть ли зависимость между уровнем дохода и возвратом кредита в срок?

In [25]:
target = data.pivot_table(index = [ 'total_income_category'], values = 'debt', aggfunc = {'count','sum'})
target = target.rename(columns={'count':'total','sum':'target'})
target['share'] = round(target['target']/target['total'], 3)
target = target.sort_values(by='share', ascending=True)
display(target)

                       total  target  share
total_income_category
D                        349      21  0.060
B                       5014     354  0.071
A                         25       2  0.080
C                      15921    1353  0.085
E                         22       2  0.091

При сравнении категорий B и C, можно заметить, что в группе людей с доходами от 50.001 до 200.000 тысяч просроченных кредитов составляет около 8.5%, в то время как у людей с доходами до 1.000.000 этот процент снижается до 7.1%. Таким образом, можно сделать вывод, что чем выше доход, тем меньше вероятность просроченных кредитов. Уровень дохода напрямую влияет на надежность заемщика и его способность своевременно выплачивать кредитные обязательства. При принятии решения о выдаче кредита следует учитывать этот фактор и предоставлять особое внимание заявкам от людей с низким доходом.

Для анализа других категорий необходимо провести дополнительные исследования, так как данных недостаточно.

### Как разные цели кредита влияют на его возврат в срок?

In [26]:
target = data.pivot_table(index = [ 'purpose_category'], values = 'debt', aggfunc = {'count','sum'})
target = target.rename(columns={'count':'total','sum':'target'})
target['share'] = round(target['target']/target['total'], 3)
target = target.sort_values(by='share', ascending=True)
display(target)

                          total  target  share
purpose_category
операции с недвижимостью  10751     780  0.073
проведение свадьбы         2313     183  0.079
операции с автомобилем     4279     400  0.093
получение образования      3988     369  0.093

Наиболее рискованными категориями целей кредита являются "автомобиль" и "образование". Доля просроченных платежей в этих категориях составляет около 9-10% клиентов, взявших кредит на автомобиль или образование, не возвращают его в срок.
С другой стороны, наиболее надежными категориями целей кредита являются "недвижимость" и "свадьба". Доля просроченных платежей в этих категориях составляет всего 7-8% клиентов, взявших кредит на недвижимость или свадьбу, не возвращают его в срок.
Таким образом, цель кредита оказывает значительное влияние на его возврат в срок. Кредиты на автомобиль и образование являются наиболее рискованными, в то время как кредиты на недвижимость и свадьбу являются наиболее надежными категориями.
</div>

### Приведите возможные причины появления пропусков в исходных данных.



В некоторых случаях они бывают из-за отсутствия доступа к определенным данным или несостоятельности источников.
Пропуски могут возникнуть из-за ошибок при записи или сборе данных, таких как технические сбои, неправильное форматирование или неработающее оборудование.
Иногда могут быть случайными или ненаблюдаемыми из-за человеческого фактора или ограничений исследования
</div>

### Объясните, почему заполнить пропуски медианным значением — лучшее решение для количественных переменных.

Использование медианного значения: 
позволяет заполнять пропуски таким образом, что это не влияет на форму или характер распределения данных;
является стабильной мерой центральной тенденции, что делает его более устойчивым к выбросам и аномалиям в данных;
позволяет сохранить уже имеющуюся информацию об относительном положении переменной в выборке;
это простой и понятный метод для замены пропущенных значений, который может быть легко применен в различных ситуациях.
</div>

## Общий вывод

В рамках проведенного исследования была проведена обширная работа над предобработкой данных. Это включало в себя удаление дубликатов, заполнение пропущенных значений и решение проблем с выбросами. Также была проведена работа по приведению переменных к одному формату и созданию новых признаков на основе имеющихся данных.

После проведения предобработки данных мы имели возможность изучить зависимости между различными факторами, такими как количество детей, семейное положение, уровнь дохода, а так же цели на кредит.

На основе проведенного анализа данных мы вывели портреты надежного и рискованного заемщика. Надежным заемщиком является человек со стабильным доходом, который состоит или ранее состоял в официальном браке, не имеющий детей, и берет кредит на недвижимость или свадьбу. Рискованным заемщиком, с другой стороны, является человек, который имеет нестабильный заработок, и берущий кредит на автомобиль или образование. Отсутствие семейного положения или нахождение в неофициальном браке также может указывать на более высокий риск невозврата кредита.

Исходя из проведенного анализа данных, мы можем предложить следующие рекомендации заказчику. При принятии решения о выдаче кредита следует учитывать цели заемщика, семейное положение и количество детей. И, наконец, рекомендуется провести дополнительный анализ данных с целью уточнения зависимости между другими факторами для более точного прогнозирования вероятности невозврата кредита.
</div>